export function landingPage(env) {
  const site = env.SITE_NAME || "GDrive CF Proxy";
  const mode = env.MODE || "signed";
  const html = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>${site}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{font-family:system-ui,-apple-system,sans-serif;max-width:760px;
       margin:40px auto;padding:0 20px;color:#222;line-height:1.55}
  h1{color:#f7931e}
  code,pre{background:#f4f4f4;padding:2px 6px;border-radius:4px;font-size:14px}
  pre{padding:14px;overflow:auto}
  .pill{display:inline-block;background:#e7f5ff;color:#1971c2;
        padding:2px 10px;border-radius:999px;font-size:12px;margin-left:6px}
  .badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;margin-right:6px}
  .b-signed{background:#d3f9d8;color:#2b8a3e}
  .b-public{background:#fff3bf;color:#7c4a02}
  footer{margin-top:40px;color:#888;font-size:13px}
</style></head><body>
<h1>🟠 ${site} <span class="pill">v2 online</span></h1>
<p>File CDN powered by Google Drive + Cloudflare. Supports images, PDFs, videos, and any file.</p>
<p>Current mode: <span class="badge b-${mode}">${mode.toUpperCase()}</span></p>

<h3>Image routes</h3>
<pre><code>/img/&lt;token&gt;
/img/&lt;token&gt;/w1200
/img/&lt;token&gt;/s0           (original)
/img/&lt;token&gt;/w800-h600-c  (cropped)</code></pre>

<h3>File routes</h3>
<pre><code>/file/&lt;token&gt;               (inline)
/file/&lt;token&gt;/report.pdf    (with filename)
/file/&lt;token&gt;?dl=1          (force download)</code></pre>

<h3>Token format</h3>
<ul>
  <li><b>Public mode:</b> raw GDrive file ID</li>
  <li><b>Signed mode:</b> <code>base64url(payload).hmac16</code> — generated by the
      <code>janchris80/laravel-cdn-signer</code> Laravel package</li>
</ul>

<h3>Other endpoints</h3>
<ul>
  <li><code>/health</code> — JSON health check</li>
</ul>

<footer>
  Hotlink protection: <b>${String(env.ENABLE_HOTLINK_PROTECTION).toLowerCase() === "true" ? "ON" : "OFF"}</b>
  · Cache TTL: <b>${env.CACHE_TTL_DAYS || 30} days</b>
  · © ${new Date().getFullYear()} ${site}
</footer>
</body></html>`;
  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
